name: DeathTpPlus
main: org.simiancage.DeathTpPlus.DeathTpPlus
version: 1.95-b${BUILD_NUMBER}
website: https://github.com/dredhorse/DeathTpPlus
authors: [Don Redhorse, orig. by. lonelydime]
description: Death commands including deathtp, deathnotify and deathstreaks.
softdepend: [Vault,CraftIRC]

commands:
    dtp:
        description: DeathTpPlus command set
permissions:
    deathtpplus.*:
        description: Gives access to all DeathTpPlus commands
        children:
            deathtpplus.deathtp: true
            deathtpplus.streak: true
            deathtpplus.deaths: true
            deathtpplus.kills: true
            deathtpplus.report: true
            deathtpplus.worldtravel: true
    deathtpplus.deathtp:
        description: Gives access to the deathtp command
        default: op
    deathtpplus.streak:
        description: Gives access to the streak command
        default: op
    deathtpplus.deaths:
        description: Gives access to the deaths command
        default: op
    deathtpplus.kills:
        description: Gives access to the kills command
        default: op
    deathtpplus.report:
    	description: Gives access to the report command
    	default: op
    deathtpplus.worldtravel:
        description: Allows teleporting to another worlds death location
        default: op
